Repository PersonligaPersson/DD2480_Group_27_CI, pull requests merged in 2022-02, with the labels that each got.

#23 Added a function that runs a shell script that lints the code. Relate…
  ci_server/server.py
  requirements.txt
  shellscripts/runLint.sh
Labels: enhancement

#27 Laid the foundations of the logging framework. Now there is a functio…
  .gitignore
  ci_server/server.py
Labels: enhancement

#26 feat: issue #14 managing cloning of specific branch
  .gitignore
  ci_server/server.py
  config/.pylintrc
Labels: enhancement

#30 Bugfix: Added a folder to host the logfiles and a build data file to …
  .gitignore
  logfiles/buildData.dat
Labels: bug

#43 Merge features
  ci_server/handler.py
  ci_server/server.py
  shellscripts/runLint.sh
Labels: enhancement

#44 Docu: Added a pdf with one paragraph describing an evaluation of our …
  Essence.pdf
Labels: documentation

#49 Commit status
  ci_server/handler.py
  ci_server/server.py
  config/.pylintrc
  tests/ci_server/log_test.py
Labels: enhancement

#54 fix: issue #53 corrected the location problem
  ci_server/handler.py
Labels: bug
